# Header
menu:
  about: /
#  writing: /writing
  speaking: /speaking
rss: /atom.xml

# Content
excerpt_link: Read More

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-112128951-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false
